import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {Button, TextField} from '@mui/material';

const inter = Inter({ subsets: ['latin'] })

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>EcoDom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p className={inter.className}>
              Projekt EcoDom+
          </p>
        </div>

        <div className={styles.center}>
          
            <form className={styles.form}>
              <div className={styles.formGroup}>
                <input className={styles.formField} type="email" id="email" name="email" placeholder='Adres email' /><br /> 
                <input className={styles.formField} type="password" id="password" name="password" placeholder='Hasło'/><br /> 
                <Button variant="contained">Login</Button>
              </div>
            </form>
          </div>
        
      </main>
    </>
  )
}
