import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {Button, TextField} from '@mui/material';
import Grid from '@mui/material/Unstable_Grid2'; // Grid version 2
import { useState } from 'react';
import Settings from '@/components/Settings';
import AddDevice from '@/components/AddDevice';
import DeviceList from '@/components/DeviceList';
const inter = Inter({ subsets: ['latin'] })

export default function Dashboard() {
    const [currentTab, setCurrentTab] = useState("default");

  return (
    <>
      <Head>
        <title>EcoDom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p className={inter.className}>
              Projekt EcoDom+
          </p>
        </div>
        <Grid container spacing={3} columns={{ xs: 4, sm: 8, md: 12 }}>
            <Grid xs="auto">
                <Button variant="contained" color="primary" onClick={() => setCurrentTab("addDevice")}>Dodaj urządzenie</Button>
            </Grid>
            <Grid xs="auto">
                <Button variant="contained" color="primary" onClick={() => setCurrentTab("deviceList")}>Lista urządzeń</Button>
            </Grid>
            <Grid xs="auto">
                <Button variant="contained" color="primary" onClick={() => setCurrentTab("settings")}>Ustawienia</Button>
            </Grid>
        </Grid>

        {currentTab == "addDevice" && (
            <AddDevice/>
        )}
        {currentTab == "deviceList" && (
            <DeviceList/>
        )}
        {currentTab == "settings" && (
            <Settings/>
        )}

        
        
      </main>
    </>
  )
}
