import Head from 'next/head'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {Button} from '@mui/material';
import Logo from "@/components/Logo";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    let login = () => {
        let email = document.getElementById('email') as HTMLInputElement;
        let password = document.getElementById('password') as HTMLInputElement;
        if (email.value == 'admin' && password.value == 'admin') {
            window.location.href = '/dashboard';
        }
    };

    return (
        <>
            <Head>
                <title>EcoDom</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main} style={{padding: 0}}>
                <div>
                    <Logo/>
                </div>
                <div>
                    <form className={styles.form}>
                        <div className={styles.formGroup}>
                            <input className={styles.formField} type="email" id="email" name="email"
                                   placeholder='Adres email'/><br/>
                            <input className={styles.formField} type="password" id="password" name="password"
                                   placeholder='Hasło'/><br/>
                            <Button variant="contained" onClick={login}>Login</Button>
                        </div>
                    </form>
                </div>
            </main>
        </>
    )
}
